<?php

namespace Database\Seeders;

use App\Models\Card;
use App\Models\Faction;
use App\Models\Attack;
use Illuminate\Database\Seeder;

class CardSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les factions
        $bronze = Faction::where('name', 'Chevaliers de Bronze')->first();
        $gold = Faction::where('name', 'Chevaliers d\'Or')->first();
        $spectres = Faction::where('name', 'Spectres d\'Hadès')->first();

        // Récupérer les attaques par nom
        $attacks = Attack::pluck('id', 'name')->toArray();

        $cards = [
            // ========================================
            // CHEVALIERS DE BRONZE (5)
            // ========================================
            [
                'name' => 'Seiya de Pegase',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'light',
                'rarity' => 'rare',
                'health_points' => 120,
                'endurance' => 80,
                'defense' => 15,
                'power' => 45,
                'cosmos' => 60,
                'cost' => 4,
                'passive_ability_name' => 'Septieme Sens',
                'passive_ability_description' => 'Quand les PV tombent sous 30%, +25% de puissance.',
                'main_attack_id' => $attacks['Pegasus Ryusei Ken'] ?? null,
                'secondary_attack_1_id' => $attacks['Pegasus Suisei Ken'] ?? null,
                'secondary_attack_2_id' => $attacks['Pegasus Rolling Crash'] ?? null,
            ],
            [
                'name' => 'Hyoga du Cygne',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'ice',
                'rarity' => 'rare',
                'health_points' => 110,
                'endurance' => 75,
                'defense' => 20,
                'power' => 40,
                'cosmos' => 65,
                'cost' => 4,
                'passive_ability_name' => 'Sang de Glace',
                'passive_ability_description' => 'Resistance aux attaques de glace +50%.',
                'main_attack_id' => $attacks['Diamond Dust'] ?? null,
                'secondary_attack_1_id' => $attacks['Aurora Thunder Attack'] ?? null,
                'secondary_attack_2_id' => $attacks['Kholodnyi Smerch'] ?? null,
            ],
            [
                'name' => 'Shiryu du Dragon',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'water',
                'rarity' => 'rare',
                'health_points' => 130,
                'endurance' => 85,
                'defense' => 25,
                'power' => 42,
                'cosmos' => 55,
                'cost' => 4,
                'passive_ability_name' => 'Bouclier du Dragon',
                'passive_ability_description' => 'Bloque la premiere attaque critique recue par combat.',
                'main_attack_id' => $attacks['Rozan Sho Ryu Ha'] ?? null,
                'secondary_attack_1_id' => $attacks['Rozan Hyaku Ryu Ha'] ?? null,
                'secondary_attack_2_id' => $attacks['Rozan Ko Ryu Ha'] ?? null,
            ],
            [
                'name' => 'Shun d\'Andromede',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'light',
                'rarity' => 'rare',
                'health_points' => 100,
                'endurance' => 70,
                'defense' => 30,
                'power' => 35,
                'cosmos' => 70,
                'cost' => 3,
                'passive_ability_name' => 'Chaine Protectrice',
                'passive_ability_description' => 'Peut proteger un allie des attaques ciblees.',
                'main_attack_id' => $attacks['Nebula Chain'] ?? null,
                'secondary_attack_1_id' => $attacks['Nebula Storm'] ?? null,
                'secondary_attack_2_id' => $attacks['Thunder Wave'] ?? null,
            ],
            [
                'name' => 'Ikki du Phenix',
                'faction_id' => $bronze->id,
                'grade' => 6,
                'armor_type' => 'bronze',
                'element' => 'fire',
                'rarity' => 'epic',
                'health_points' => 140,
                'endurance' => 90,
                'defense' => 18,
                'power' => 55,
                'cosmos' => 75,
                'cost' => 5,
                'passive_ability_name' => 'Resurrection du Phenix',
                'passive_ability_description' => 'Revient une fois avec 30% de PV apres KO.',
                'main_attack_id' => $attacks['Ho Yoku Tensho'] ?? null,
                'secondary_attack_1_id' => $attacks['Phoenix Genma Ken'] ?? null,
                'secondary_attack_2_id' => $attacks['Thunder Claw'] ?? null,
            ],

            // ========================================
            // CHEVALIERS D'OR (12)
            // ========================================
            [
                'name' => 'Mu du Belier',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 160,
                'endurance' => 80,
                'defense' => 40,
                'power' => 65,
                'cosmos' => 100,
                'cost' => 6,
                'passive_ability_name' => 'Reparateur d\'Armures',
                'passive_ability_description' => 'Restaure 10 PV a tous les allies chaque tour.',
                'main_attack_id' => $attacks['Stardust Revolution'] ?? null,
                'secondary_attack_1_id' => $attacks['Crystal Wall'] ?? null,
                'secondary_attack_2_id' => $attacks['Starlight Extinction'] ?? null,
            ],
            [
                'name' => 'Aldebaran du Taureau',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'earth',
                'rarity' => 'legendary',
                'health_points' => 220,
                'endurance' => 100,
                'defense' => 45,
                'power' => 80,
                'cosmos' => 75,
                'cost' => 7,
                'passive_ability_name' => 'Force Titanesque',
                'passive_ability_description' => 'Les attaques physiques infligent +20% de degats.',
                'main_attack_id' => $attacks['Great Horn'] ?? null,
                'secondary_attack_1_id' => $attacks['Titan\'s Nova'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Saga des Gemeaux',
                'faction_id' => $gold->id,
                'grade' => 9,
                'armor_type' => 'gold',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 200,
                'endurance' => 110,
                'defense' => 30,
                'power' => 85,
                'cosmos' => 100,
                'cost' => 8,
                'passive_ability_name' => 'Dualite',
                'passive_ability_description' => 'Peut changer d\'element (lumiere/tenebres) une fois par combat.',
                'main_attack_id' => $attacks['Galaxian Explosion'] ?? null,
                'secondary_attack_1_id' => $attacks['Another Dimension'] ?? null,
                'secondary_attack_2_id' => $attacks['Demon Emperor Fist'] ?? null,
            ],
            [
                'name' => 'Death Mask du Cancer',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 165,
                'endurance' => 85,
                'defense' => 28,
                'power' => 70,
                'cosmos' => 90,
                'cost' => 6,
                'passive_ability_name' => 'Masque Mortuaire',
                'passive_ability_description' => 'Les ennemis vaincus augmentent sa puissance de 10%.',
                'main_attack_id' => $attacks['Sekishiki Meikai Ha'] ?? null,
                'secondary_attack_1_id' => $attacks['Praesepe Underworld Waves'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Aiolia du Lion',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'thunder',
                'rarity' => 'legendary',
                'health_points' => 180,
                'endurance' => 100,
                'defense' => 35,
                'power' => 75,
                'cosmos' => 90,
                'cost' => 7,
                'passive_ability_name' => 'Fierte du Lion',
                'passive_ability_description' => '+15% de degats quand aucun allie n\'est KO.',
                'main_attack_id' => $attacks['Lightning Plasma'] ?? null,
                'secondary_attack_1_id' => $attacks['Lightning Bolt'] ?? null,
                'secondary_attack_2_id' => $attacks['Photon Burst'] ?? null,
            ],
            [
                'name' => 'Shaka de la Vierge',
                'faction_id' => $gold->id,
                'grade' => 9,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 170,
                'endurance' => 90,
                'defense' => 35,
                'power' => 80,
                'cosmos' => 120,
                'cost' => 8,
                'passive_ability_name' => 'Homme le plus proche de Dieu',
                'passive_ability_description' => 'Immunise aux effets de debuff. +30% cosmos.',
                'main_attack_id' => $attacks['Tenbu Horin'] ?? null,
                'secondary_attack_1_id' => $attacks['Tenma Kofuku'] ?? null,
                'secondary_attack_2_id' => $attacks['Rikudo Rinne'] ?? null,
            ],
            [
                'name' => 'Dohko de la Balance',
                'faction_id' => $gold->id,
                'grade' => 9,
                'armor_type' => 'gold',
                'element' => 'water',
                'rarity' => 'legendary',
                'health_points' => 190,
                'endurance' => 110,
                'defense' => 40,
                'power' => 75,
                'cosmos' => 95,
                'cost' => 8,
                'passive_ability_name' => 'Sagesse Millenaire',
                'passive_ability_description' => 'Peut utiliser les armes de la Balance. +20% defense.',
                'main_attack_id' => $attacks['Rozan Hyaku Ryu Ha Master'] ?? null,
                'secondary_attack_1_id' => $attacks['Rozan Ko Ryu Ha Master'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Milo du Scorpion',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'fire',
                'rarity' => 'legendary',
                'health_points' => 170,
                'endurance' => 95,
                'defense' => 28,
                'power' => 70,
                'cosmos' => 85,
                'cost' => 7,
                'passive_ability_name' => 'Antares',
                'passive_ability_description' => 'Chaque attaque empile une piqure. A 15, degats doubles.',
                'main_attack_id' => $attacks['Scarlet Needle'] ?? null,
                'secondary_attack_1_id' => $attacks['Scarlet Needle Antares'] ?? null,
                'secondary_attack_2_id' => $attacks['Restriction'] ?? null,
            ],
            [
                'name' => 'Aiolos du Sagittaire',
                'faction_id' => $gold->id,
                'grade' => 9,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 185,
                'endurance' => 100,
                'defense' => 32,
                'power' => 82,
                'cosmos' => 95,
                'cost' => 8,
                'passive_ability_name' => 'Fleche d\'Or',
                'passive_ability_description' => 'Les attaques a distance ignorent 30% de la defense.',
                'main_attack_id' => $attacks['Atomic Thunderbolt'] ?? null,
                'secondary_attack_1_id' => $attacks['Infinity Break'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Shura du Capricorne',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 175,
                'endurance' => 90,
                'defense' => 32,
                'power' => 80,
                'cosmos' => 80,
                'cost' => 7,
                'passive_ability_name' => 'Lame Sacree',
                'passive_ability_description' => 'Ignore 20% de la defense ennemie.',
                'main_attack_id' => $attacks['Excalibur'] ?? null,
                'secondary_attack_1_id' => $attacks['Jumping Stone'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Camus du Verseau',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'ice',
                'rarity' => 'legendary',
                'health_points' => 165,
                'endurance' => 85,
                'defense' => 30,
                'power' => 72,
                'cosmos' => 95,
                'cost' => 7,
                'passive_ability_name' => 'Zero Absolu',
                'passive_ability_description' => 'Les attaques de glace ont +30% de chance de geler.',
                'main_attack_id' => $attacks['Aurora Execution'] ?? null,
                'secondary_attack_1_id' => $attacks['Freezing Coffin'] ?? null,
                'secondary_attack_2_id' => $attacks['Diamond Dust'] ?? null,
            ],
            [
                'name' => 'Aphrodite des Poissons',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'earth',
                'rarity' => 'legendary',
                'health_points' => 155,
                'endurance' => 80,
                'defense' => 25,
                'power' => 68,
                'cosmos' => 90,
                'cost' => 6,
                'passive_ability_name' => 'Chemin des Roses',
                'passive_ability_description' => 'Les ennemis subissent des degats de poison chaque tour.',
                'main_attack_id' => $attacks['Bloody Rose'] ?? null,
                'secondary_attack_1_id' => $attacks['Royal Demon Rose'] ?? null,
                'secondary_attack_2_id' => $attacks['Piranha Rose'] ?? null,
            ],

            // ========================================
            // SPECTRES D'HADES (13)
            // ========================================
            [
                'name' => 'Charon de l\'Acheron',
                'faction_id' => $spectres->id,
                'grade' => 5,
                'armor_type' => 'surplis',
                'element' => 'water',
                'rarity' => 'rare',
                'health_points' => 130,
                'endurance' => 75,
                'defense' => 22,
                'power' => 50,
                'cosmos' => 55,
                'cost' => 4,
                'passive_ability_name' => 'Passeur des Enfers',
                'passive_ability_description' => 'Gagne du cosmos a chaque ennemi vaincu.',
                'main_attack_id' => $attacks['Rolling Oar'] ?? null,
                'secondary_attack_1_id' => $attacks['Eddying Current Crusher'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Queen de l\'Alraune',
                'faction_id' => $spectres->id,
                'grade' => 5,
                'armor_type' => 'surplis',
                'element' => 'earth',
                'rarity' => 'rare',
                'health_points' => 115,
                'endurance' => 70,
                'defense' => 20,
                'power' => 48,
                'cosmos' => 60,
                'cost' => 3,
                'passive_ability_name' => 'Epines Veneneuses',
                'passive_ability_description' => 'Les attaques infligent un poison qui dure 3 tours.',
                'main_attack_id' => $attacks['Cursed Thorn'] ?? null,
                'secondary_attack_1_id' => $attacks['Blood Flower Scissors'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Lune de Balron',
                'faction_id' => $spectres->id,
                'grade' => 6,
                'armor_type' => 'surplis',
                'element' => 'fire',
                'rarity' => 'epic',
                'health_points' => 140,
                'endurance' => 80,
                'defense' => 25,
                'power' => 55,
                'cosmos' => 70,
                'cost' => 5,
                'passive_ability_name' => 'Maitre des Ames',
                'passive_ability_description' => 'Peut controler un ennemi faible pendant 1 tour.',
                'main_attack_id' => $attacks['Reincarnation'] ?? null,
                'secondary_attack_1_id' => $attacks['Fire Whip'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Sylphide de Basilic',
                'faction_id' => $spectres->id,
                'grade' => 5,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'rare',
                'health_points' => 125,
                'endurance' => 75,
                'defense' => 22,
                'power' => 52,
                'cosmos' => 58,
                'cost' => 4,
                'passive_ability_name' => 'Regard Petrifiant',
                'passive_ability_description' => '10% de chance de paralyser l\'ennemi en debut de tour.',
                'main_attack_id' => $attacks['Annihilation Flap'] ?? null,
                'secondary_attack_1_id' => $attacks['Deadly Poison Breath'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Niobe de Deep',
                'faction_id' => $spectres->id,
                'grade' => 5,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'rare',
                'health_points' => 110,
                'endurance' => 70,
                'defense' => 18,
                'power' => 45,
                'cosmos' => 65,
                'cost' => 3,
                'passive_ability_name' => 'Parfum Hypnotique',
                'passive_ability_description' => 'Les ennemis ont -15% de precision.',
                'main_attack_id' => $attacks['Deep Fragrance'] ?? null,
                'secondary_attack_1_id' => $attacks['Deep Sleep'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Aiacos de Garuda',
                'faction_id' => $spectres->id,
                'grade' => 9,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 195,
                'endurance' => 105,
                'defense' => 35,
                'power' => 85,
                'cosmos' => 95,
                'cost' => 8,
                'passive_ability_name' => 'Juge des Enfers',
                'passive_ability_description' => '+20% de degats contre les Chevaliers d\'Or.',
                'main_attack_id' => $attacks['Garuda Flap'] ?? null,
                'secondary_attack_1_id' => $attacks['Galactica Illusion'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Gigant du Cyclope',
                'faction_id' => $spectres->id,
                'grade' => 6,
                'armor_type' => 'surplis',
                'element' => 'earth',
                'rarity' => 'epic',
                'health_points' => 180,
                'endurance' => 90,
                'defense' => 30,
                'power' => 65,
                'cosmos' => 60,
                'cost' => 5,
                'passive_ability_name' => 'Force Colossale',
                'passive_ability_description' => '+25% de degats physiques, -10% vitesse.',
                'main_attack_id' => $attacks['Black Death Fist'] ?? null,
                'secondary_attack_1_id' => $attacks['Gigantic Feathers Flap'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Minos du Griffon',
                'faction_id' => $spectres->id,
                'grade' => 9,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 190,
                'endurance' => 100,
                'defense' => 32,
                'power' => 80,
                'cosmos' => 98,
                'cost' => 8,
                'passive_ability_name' => 'Juge des Enfers',
                'passive_ability_description' => 'Controle les mouvements de l\'ennemi.',
                'main_attack_id' => $attacks['Cosmic Marionettion'] ?? null,
                'secondary_attack_1_id' => $attacks['Griffon Feathers Flap'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Valentine de la Harpie',
                'faction_id' => $spectres->id,
                'grade' => 5,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'rare',
                'health_points' => 120,
                'endurance' => 72,
                'defense' => 20,
                'power' => 50,
                'cosmos' => 62,
                'cost' => 4,
                'passive_ability_name' => 'Devotion a Rhadamanthe',
                'passive_ability_description' => '+15% de puissance quand Rhadamanthe est sur le terrain.',
                'main_attack_id' => $attacks['Greed the Life'] ?? null,
                'secondary_attack_1_id' => $attacks['Sweet Chocolate'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Pandore',
                'faction_id' => $spectres->id,
                'grade' => 7,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'epic',
                'health_points' => 150,
                'endurance' => 85,
                'defense' => 28,
                'power' => 60,
                'cosmos' => 85,
                'cost' => 6,
                'passive_ability_name' => 'Soeur d\'Hades',
                'passive_ability_description' => 'Booste tous les Spectres allies de +10% puissance.',
                'main_attack_id' => $attacks['Balance of Curse'] ?? null,
                'secondary_attack_1_id' => $attacks['Dark Serenade'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Myu du Papillon',
                'faction_id' => $spectres->id,
                'grade' => 6,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'epic',
                'health_points' => 145,
                'endurance' => 82,
                'defense' => 24,
                'power' => 58,
                'cosmos' => 75,
                'cost' => 5,
                'passive_ability_name' => 'Metamorphose',
                'passive_ability_description' => 'Change de forme apres avoir recu 50% de degats. +30% stats.',
                'main_attack_id' => $attacks['Ugly Eruption'] ?? null,
                'secondary_attack_1_id' => $attacks['Fairy Thronging'] ?? null,
                'secondary_attack_2_id' => $attacks['Silky Thread'] ?? null,
            ],
            [
                'name' => 'Pharaoh du Sphinx',
                'faction_id' => $spectres->id,
                'grade' => 6,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'epic',
                'health_points' => 155,
                'endurance' => 85,
                'defense' => 26,
                'power' => 62,
                'cosmos' => 78,
                'cost' => 5,
                'passive_ability_name' => 'Gardien des Ames',
                'passive_ability_description' => 'Juge les ames des ennemis vaincus. Regenere 15 PV.',
                'main_attack_id' => $attacks['Balance of Curse Sphinx'] ?? null,
                'secondary_attack_1_id' => $attacks['Harp of Hades'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Rhadamanthe de la Wyvern',
                'faction_id' => $spectres->id,
                'grade' => 9,
                'armor_type' => 'surplis',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 200,
                'endurance' => 105,
                'defense' => 38,
                'power' => 88,
                'cosmos' => 95,
                'cost' => 8,
                'passive_ability_name' => 'Juge Supreme des Enfers',
                'passive_ability_description' => '+25% de degats contre les Chevaliers d\'Or. Chef des 3 Juges.',
                'main_attack_id' => $attacks['Greatest Caution'] ?? null,
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],

            // ========================================
            // DIEUX (5)
            // ========================================
            [
                'name' => 'Athena',
                'faction_id' => $bronze->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 250,
                'endurance' => 120,
                'defense' => 50,
                'power' => 90,
                'cosmos' => 150,
                'cost' => 10,
                'passive_ability_name' => 'Deesse de la Sagesse',
                'passive_ability_description' => 'Tous les allies gagnent +20% defense et regenerent 15 PV/tour.',
                'main_attack_id' => $attacks['Athena Exclamation'] ?? null,
                'secondary_attack_1_id' => $attacks['Aegis Shield'] ?? null,
                'secondary_attack_2_id' => $attacks['Nike Staff'] ?? null,
            ],
            [
                'name' => 'Hades',
                'faction_id' => $spectres->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 280,
                'endurance' => 130,
                'defense' => 48,
                'power' => 100,
                'cosmos' => 140,
                'cost' => 10,
                'passive_ability_name' => 'Dieu des Enfers',
                'passive_ability_description' => 'Immunise aux effets de statut negatifs. +30% degats sur terrain.',
                'main_attack_id' => $attacks['Terrible Providence'] ?? null,
                'secondary_attack_1_id' => $attacks['Greatest Eclipse'] ?? null,
                'secondary_attack_2_id' => $attacks['Sword of Hades'] ?? null,
            ],
            [
                'name' => 'Poseidon',
                'faction_id' => $spectres->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'water',
                'rarity' => 'legendary',
                'health_points' => 270,
                'endurance' => 125,
                'defense' => 45,
                'power' => 95,
                'cosmos' => 135,
                'cost' => 10,
                'passive_ability_name' => 'Dieu des Mers',
                'passive_ability_description' => 'Les attaques eau font +40% de degats. Invoque des raz-de-maree.',
                'main_attack_id' => $attacks['Poseidon\'s Wrath'] ?? null,
                'secondary_attack_1_id' => $attacks['Tidal Wave'] ?? null,
                'secondary_attack_2_id' => $attacks['Trident Strike'] ?? null,
            ],
            [
                'name' => 'Hypnos',
                'faction_id' => $spectres->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 240,
                'endurance' => 115,
                'defense' => 42,
                'power' => 88,
                'cosmos' => 145,
                'cost' => 9,
                'passive_ability_name' => 'Dieu du Sommeil',
                'passive_ability_description' => 'Les ennemis ont 25% de chance d\'etre endormis chaque tour.',
                'main_attack_id' => $attacks['Eternal Drowsiness'] ?? null,
                'secondary_attack_1_id' => $attacks['Encounter Another Field'] ?? null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Thanatos',
                'faction_id' => $spectres->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 260,
                'endurance' => 120,
                'defense' => 40,
                'power' => 105,
                'cosmos' => 140,
                'cost' => 9,
                'passive_ability_name' => 'Dieu de la Mort',
                'passive_ability_description' => 'Les ennemis sous 20% de PV sont instantanement elimines.',
                'main_attack_id' => $attacks['Death Touch'] ?? null,
                'secondary_attack_1_id' => $attacks['Thanatos Terrible Providence'] ?? null,
                'secondary_attack_2_id' => $attacks['Tartarus Phobia'] ?? null,
            ],
        ];

        foreach ($cards as $card) {
            Card::create($card);
        }
    }
}