<?php

namespace Database\Seeders;

use App\Models\Card;
use App\Models\Faction;
use App\Models\Attack;
use Illuminate\Database\Seeder;

class CardSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les factions
        $bronze = Faction::where('name', 'Chevaliers de Bronze')->first();
        $silver = Faction::where('name', 'Chevaliers d\'Argent')->first();
        $gold = Faction::where('name', 'Chevaliers d\'Or')->first();
        $spectres = Faction::where('name', 'Spectres d\'Hadès')->first();
        $marinas = Faction::where('name', 'Marinas de Poséidon')->first();
        $asgard = Faction::where('name', 'Guerriers Divins d\'Asgard')->first();

        // Récupérer les attaques par nom
        $attacks = Attack::pluck('id', 'name')->toArray();

        $cards = [
            // Chevaliers de Bronze
            [
                'name' => 'Seiya de Pégase',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'light',
                'rarity' => 'rare',
                'health_points' => 120,
                'endurance' => 80,
                'defense' => 15,
                'power' => 45,
                'cosmos' => 60,
                'cost' => 4,
                'passive_ability_name' => 'Septième Sens',
                'passive_ability_description' => 'Quand les PV tombent sous 30%, +25% de puissance.',
                'main_attack_id' => $attacks['Pegasus Ryusei Ken'],
                'secondary_attack_1_id' => $attacks['Pegasus Suisei Ken'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Hyōga du Cygne',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'ice',
                'rarity' => 'rare',
                'health_points' => 110,
                'endurance' => 75,
                'defense' => 20,
                'power' => 40,
                'cosmos' => 65,
                'cost' => 4,
                'passive_ability_name' => 'Sang de Glace',
                'passive_ability_description' => 'Résistance aux attaques de glace +50%.',
                'main_attack_id' => $attacks['Diamond Dust'],
                'secondary_attack_1_id' => $attacks['Aurora Thunder Attack'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Shiryū du Dragon',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'water',
                'rarity' => 'rare',
                'health_points' => 130,
                'endurance' => 85,
                'defense' => 25,
                'power' => 42,
                'cosmos' => 55,
                'cost' => 4,
                'passive_ability_name' => 'Bouclier du Dragon',
                'passive_ability_description' => 'Bloque la première attaque critique reçue.',
                'main_attack_id' => $attacks['Rozan Shō Ryū Ha'],
                'secondary_attack_1_id' => $attacks['Rozan Hyaku Ryū Ha'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Shun d\'Andromède',
                'faction_id' => $bronze->id,
                'grade' => 5,
                'armor_type' => 'bronze',
                'element' => 'light',
                'rarity' => 'rare',
                'health_points' => 100,
                'endurance' => 70,
                'defense' => 30,
                'power' => 35,
                'cosmos' => 70,
                'cost' => 3,
                'passive_ability_name' => 'Chaîne Protectrice',
                'passive_ability_description' => 'Peut protéger un allié des attaques ciblées.',
                'main_attack_id' => $attacks['Nebula Chain'],
                'secondary_attack_1_id' => $attacks['Crystal Wall'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Ikki du Phénix',
                'faction_id' => $bronze->id,
                'grade' => 6,
                'armor_type' => 'bronze',
                'element' => 'fire',
                'rarity' => 'epic',
                'health_points' => 140,
                'endurance' => 90,
                'defense' => 18,
                'power' => 55,
                'cosmos' => 75,
                'cost' => 5,
                'passive_ability_name' => 'Résurrection du Phénix',
                'passive_ability_description' => 'Revient une fois avec 30% de PV après KO.',
                'main_attack_id' => $attacks['Phoenix Genma Ken'],
                'secondary_attack_1_id' => $attacks['Thunder Claw'],
                'secondary_attack_2_id' => null,
            ],

            // Chevaliers d'Or
            [
                'name' => 'Aiolia du Lion',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'thunder',
                'rarity' => 'legendary',
                'health_points' => 180,
                'endurance' => 100,
                'defense' => 35,
                'power' => 75,
                'cosmos' => 90,
                'cost' => 7,
                'passive_ability_name' => 'Fierté du Lion',
                'passive_ability_description' => '+15% de dégâts quand aucun allié n\'est KO.',
                'main_attack_id' => $attacks['Lightning Bolt'],
                'secondary_attack_1_id' => $attacks['Lightning Plasma'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Saga des Gémeaux',
                'faction_id' => $gold->id,
                'grade' => 9,
                'armor_type' => 'gold',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 200,
                'endurance' => 110,
                'defense' => 30,
                'power' => 85,
                'cosmos' => 100,
                'cost' => 8,
                'passive_ability_name' => 'Dualité',
                'passive_ability_description' => 'Peut changer d\'élément une fois par combat.',
                'main_attack_id' => $attacks['Galaxian Explosion'],
                'secondary_attack_1_id' => $attacks['Phoenix Genma Ken'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Milo du Scorpion',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'fire',
                'rarity' => 'legendary',
                'health_points' => 170,
                'endurance' => 95,
                'defense' => 28,
                'power' => 70,
                'cosmos' => 85,
                'cost' => 7,
                'passive_ability_name' => 'Antares',
                'passive_ability_description' => 'La 15ème piqûre inflige des dégâts doublés.',
                'main_attack_id' => $attacks['Scarlet Needle'],
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Shura du Capricorne',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 175,
                'endurance' => 90,
                'defense' => 32,
                'power' => 80,
                'cosmos' => 80,
                'cost' => 7,
                'passive_ability_name' => 'Lame Sacrée',
                'passive_ability_description' => 'Ignore 20% de la défense ennemie.',
                'main_attack_id' => $attacks['Excalibur'],
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Camus du Verseau',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'ice',
                'rarity' => 'legendary',
                'health_points' => 165,
                'endurance' => 85,
                'defense' => 30,
                'power' => 72,
                'cosmos' => 95,
                'cost' => 7,
                'passive_ability_name' => 'Zéro Absolu',
                'passive_ability_description' => 'Les attaques de glace ont +30% de chance de geler.',
                'main_attack_id' => $attacks['Aurora Execution'],
                'secondary_attack_1_id' => $attacks['Diamond Dust'],
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Mū du Bélier',
                'faction_id' => $gold->id,
                'grade' => 8,
                'armor_type' => 'gold',
                'element' => 'light',
                'rarity' => 'legendary',
                'health_points' => 160,
                'endurance' => 80,
                'defense' => 40,
                'power' => 65,
                'cosmos' => 100,
                'cost' => 6,
                'passive_ability_name' => 'Réparateur d\'Armures',
                'passive_ability_description' => 'Restaure 10 PV à tous les alliés chaque tour.',
                'main_attack_id' => $attacks['Stardust Revolution'],
                'secondary_attack_1_id' => $attacks['Crystal Wall'],
                'secondary_attack_2_id' => null,
            ],

            // Spectres
            [
                'name' => 'Rhadamanthe de la Wyvern',
                'faction_id' => $spectres->id,
                'grade' => 9,
                'armor_type' => 'divine',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 190,
                'endurance' => 100,
                'defense' => 35,
                'power' => 82,
                'cosmos' => 90,
                'cost' => 8,
                'passive_ability_name' => 'Juge des Enfers',
                'passive_ability_description' => '+20% de dégâts contre les Chevaliers d\'Or.',
                'main_attack_id' => $attacks['Greatest Caution'],
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Hadès',
                'faction_id' => $spectres->id,
                'grade' => 10,
                'armor_type' => 'divine',
                'element' => 'darkness',
                'rarity' => 'legendary',
                'health_points' => 250,
                'endurance' => 120,
                'defense' => 45,
                'power' => 100,
                'cosmos' => 120,
                'cost' => 10,
                'passive_ability_name' => 'Dieu des Enfers',
                'passive_ability_description' => 'Immunisé aux effets de statut négatifs.',
                'main_attack_id' => $attacks['Terrible Providence'],
                'secondary_attack_1_id' => $attacks['Greatest Caution'],
                'secondary_attack_2_id' => null,
            ],

            // Cartes communes pour compléter
            [
                'name' => 'Soldat du Sanctuaire',
                'faction_id' => $bronze->id,
                'grade' => 1,
                'armor_type' => 'bronze',
                'element' => 'light',
                'rarity' => 'common',
                'health_points' => 50,
                'endurance' => 40,
                'defense' => 5,
                'power' => 15,
                'cosmos' => 20,
                'cost' => 1,
                'passive_ability_name' => null,
                'passive_ability_description' => null,
                'main_attack_id' => $attacks['Pegasus Ryusei Ken'],
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],
            [
                'name' => 'Garde d\'Argent',
                'faction_id' => $silver->id,
                'grade' => 3,
                'armor_type' => 'silver',
                'element' => 'light',
                'rarity' => 'common',
                'health_points' => 80,
                'endurance' => 55,
                'defense' => 12,
                'power' => 28,
                'cosmos' => 35,
                'cost' => 2,
                'passive_ability_name' => null,
                'passive_ability_description' => null,
                'main_attack_id' => $attacks['Lightning Bolt'],
                'secondary_attack_1_id' => null,
                'secondary_attack_2_id' => null,
            ],
        ];

        foreach ($cards as $card) {
            Card::create($card);
        }
    }
}